### PR TITLE
add go binding vanity import html file

### PR DESCRIPTION
**Pull request by raphi011**
Hi - please upload this to the go.libelektra.org subdomain :)

### CODE REVIEW

**Comment by markus2330** [comment]
So we do not need to merge this anymore and instead I make a redirect from go.libelektra.org -> https://github.com/ElektraInitiative/go-elektra?

**Comment by raphi011** [comment]
@markus2330 if this file is served from `go.libelektra.org` the vanity import should work. Can you upload it?

**Comment by markus2330** [comment]
Isn't it the better/easier strategy to directly redirect to https://github.com/ElektraInitiative/go-elektra

**Comment by raphi011** [comment]
> Isn't it the better/easier strategy to directly redirect to https://github.com/ElektraInitiative/go-elektra

Not sure if that works. But you can give it a try

**Comment by markus2330** [comment]
I created the redirect.

**Comment by raphi011** [comment]
> package go.libelektra.org: unrecognized import path "go.libelektra.org" (parse https://go.libelektra.org?go-get=1: no go-import meta tags (meta tag github.com/ElektraInitiative/go-elektra did not match import path go.libelektra.org))

doesn't work unfortunately

**Comment by markus2330** [comment]
`curl https://go.libelektra.org/` gives now the file of this PR

**Pull request merged**
